### ISSUE TITLE
Issues compiling since commit `ca34690`

### ISSUE THREAD

**Issue by r4j4h** [boformer/LegacyNetworkSkins#2]
I am experiencing some errors trying to compile the .dll for this project.

The errors are very limited and came in a commit 8 days ago. I will list one and keep the rest until you ask, as just the one may be sufficient.

The smallest, easiest of them is from line 19 of `NetworkSkinsMod.cs:

```
public string Name => "Network Skins";
```

Error List Output

```
Error   4   ; expected  C:\Users\jasmine\git.repos\r4j4h\NetworkSkins\NetworkSkins\NetworkSkinsMod.cs   19  28  NetworkSkins
```

This is my first time trying to compile, but going backwards in history I found the code compiles fine if I set my HEAD to before these lines were changed to utilize the => lambda expressions.

My C# is extremely rusty so I don't know if they are the problem but I presume they are fine and I jut need some configuration to inform VS2013 that these lines are valid, so I wanted to ask for help. :-)

**Comment by boformer** [comment]
This happens because the mod uses newer features of the C# language (but still .NET Framework 3.5).

I will see if I can change it in the next commit.

Follow this how-to to do it yourself: http://www.codeproject.com/Tips/865579/How-to-change-targeted-Csharp-version-in-Visual-St

**Comment by r4j4h** [comment]
Ah, thank you, you are absolutely correct. Unfortunately I cannot change it to the correct version as Visual Studio 2013 only goes up to C# 5.0. >_< I will see if the future commit helps otherwise I will have to see what I can do.

**Comment by r4j4h** [comment]
Ah, thank you, you are absolutely correct. Unfortunately I cannot change it to the correct version as Visual Studio 2013 only goes up to C# 5.0. >_<

**Comment by boformer** [comment]
Get the latest Community Version.
